// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF4QKVbbr02w7-KnUSxVxBTBEnilTPI9M',
    appId: '1:249919690713:web:e963ec2448c43ac689abc8',
    messagingSenderId: '249919690713',
    projectId: 'batch4-7757c',
    authDomain: 'batch4-7757c.firebaseapp.com',
    storageBucket: 'batch4-7757c.firebasestorage.app',
    measurementId: 'G-F0J29V40WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvVU58XPJFKlpSMO3KHAuQLxdHfEfm9sQ',
    appId: '1:249919690713:android:b10ffb7c18bafffc89abc8',
    messagingSenderId: '249919690713',
    projectId: 'batch4-7757c',
    storageBucket: 'batch4-7757c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD9clTkbH8Y3Qu7Hf4teXMx6ocPer359c',
    appId: '1:249919690713:ios:91829da40f8d101c89abc8',
    messagingSenderId: '249919690713',
    projectId: 'batch4-7757c',
    storageBucket: 'batch4-7757c.firebasestorage.app',
    iosBundleId: 'com.app.myapp',
  );
}
